### PR TITLE
[WIP] JSON data source for Data List

### PR DESCRIPTION
**Pull request by leekelleher**
I started working on a JSON data source for the Data List editor, but I got stuck with the JSONPath bits - I couldn't figure it out.

Tagging with "Help wanted" aka "Up for grabs". 🙏

### CODE REVIEW

**Comment by greystate** [comment]
I'm sure @Hendy must've done something in the nuPickers JSON pickers and have an insight or two?

**Comment by leekelleher** [comment]
No matter how many times I try to understand JSONPath, something isn't clicking with me.
I'm using this doco for reference: <https://goessner.net/articles/JsonPath/index.html>

The example I was trying to use was a simple country code/name listing: <http://country.io/names.json>

I got as far as setting the JSONPath for the item, (e.g. `$.*`), but then how to get the key (property name) from that item? and how to get the value?

My assumption is that JSONPath is purposed more for structured data, where you are only interested in the values, rather than reflectively getting keys/names. _Or maybe I'm using a poor example? But it's still JSON, right?_ 🤷‍♂

**Comment by bjarnef** [comment]
@leekelleher regarding Data List editor I had a look at the docs here https://github.com/leekelleher/umbraco-contentment/blob/master/docs/editors/data-list.md 

Would it make sense to add a `Disabled` property to `DataListItem`, e.g. to set this based on a condition?
https://github.com/leekelleher/umbraco-contentment/blob/master/src/Umbraco.Community.Contentment/DataEditors/DataList/DataListItem.cs

Both checkbox, radiobutton and dropdownlist support disabled state and I think it is possible to set disabled of Content Picker using filter property (function).

**Comment by renetruelsen** [comment]
Hey Lee.

I'm currently working on this one. I'm going with the idea that we'll need to support different types of JSON ( array and object ), and I'll use the JSONPath as exampled here: https://restfulapi.net/json-jsonpath/
I'm using the book-json-example in the mentioned link to test with, along with a more complex json-data retrieved from local systems. If you have a specific case that needs tested, please let me know.

**Comment by leekelleher** [comment]
@renetruelsen Thanks for picking up on this one. Like I say above, I've been struggling with JSONPath.

In terms of use-cases, I was mostly playing around with http://country.io/names.json - but see how you get on with the book-json example 👍

**Comment by renetruelsen** [comment]
@leekelleher 
Yeah, I look at that example as well. The problem is that this specific example isn't prudent to be parsed into an array using JSON Path. You can definately handle it using code, but by JSONPath alone data like that would/should normally be delivered in the terms of: 
https://gist.githubusercontent.com/keeguon/2310008/raw/bdc2ce1c1e3f28f9cab5b4393c7549f38361be4e/countries.json

**Comment by renetruelsen** [comment]
With the latter example I would use the json paths:
                ItemsJsonPath = @"$..[*]"
                NameJsonPath = @"$.name"
                ValueJsonPath = @"$.code"
Which would return proper values .
Should I do a PR which supports this "proper json", or do you also want http://country.io/names.json to work? ...which I cannot see how :-)

**Comment by leekelleher** [comment]
@renetruelsen I'm happy with "proper json" 😄  I'm not precious about the country.io JSON, it was just something I'd found a while back.

We'll need to document the difference between using JSON arrays vs a single object (with lots of properties).

In terms of the PR, make sure to target the "dev/wip/json-datasource" branch 👍

**Comment by renetruelsen** [comment]
Absolutely. Got a PR ready. But before I send it, could you please merge this branch with the master branch?

**Comment by leekelleher** [comment]
@renetruelsen I've merged the "master" branch into "dev/wip/json-datasource". Made a couple of amends so it compiles.  I also got Dependency Injection to work with the data-sources, so have replaced the `Current.Logger` line.

**Comment by leekelleher** [comment]
PR #19 has been merged in to this branch. Merging in this PR now.

**Pull request merged**
