### PR TITLE
Added Translation Dictionary support to UmbracoContentTypesDataListSource

### PR DESCRIPTION
**Pull request by jerpenol**

### CODE REVIEW

**Review by leekelleher — COMMENTED** [review]
Thank you for the PR @jerpenol, it is much appreciated.

Contentment is still supporting Umbraco v8, do we know if this code would on it too? I'll need to review at some point.

**Comment by jerpenol** [comment]
@leekelleher Both the ILocalizationTextService as the ICultureDictionary are available in 8.18. Not sure though if fetching the ICultureDictionary works differently.

**Comment by leekelleher** [comment]
@jerpenol I've updated your PR to also include support for Umbraco v8.x.

I've provisionally tested this against Umbraco v8.17.0, v10.0.0 and v11.0.0, which all appear to work as expected.

Once you're happy, you can set the PR as "Ready to review".

**Comment by leekelleher** [comment]
@jerpenol Just to let you know that I've finally got a patch release out with this fix, [Contentment v4.4.5](https://github.com/leekelleher/umbraco-contentment/releases/tag/4.4.5). Thanks again!

**Pull request merged**
