### PR TITLE
ConfigurationEditorOverlay: Make use of Umbraco directives and change <a> to <button>

### PR DESCRIPTION
**Pull request by BatJan**
### Description

I have changed `<a>` to `<button>` and replaced `<i>` with `<umb-icon>` directive and I have replaced the search filter markup with the `<umb-search-filter>` directive instead. Finally I have deleted the styling rule for the Umbraco icon setting it's height limit to 30pixels even though the .large class says to make the icons 32x32 pixels meaning the Umbraco icon would look like it was cut off in the bottom - So removed that selector from the file.

### Types of changes

- [ ] Documentation change
- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_

### Checklist

- [x] My code follows the coding style of this project.
- [x] My changes generate no new warnings.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the corresponding documentation.
- [x] I have read the **[CONTRIBUTING](CONTRIBUTING)** and **[CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)** documents.

### CODE REVIEW

**Comment by leekelleher** [comment]
Thank you @BatJan! 🎉 

Do you know which Umbraco version the `<umb-icon>` directive was introduced?

Currently Contentment builds against v8.6.1 _(as that was the latest version at the time of my initial release)._ I'm considering bumping my Umbraco version dependency, but just need to figure out my own version numbering, _(as with SemVer that'd be a v2.0)._ Nothing for you to worry about though, it's more about logistics for me. 😃 

With the Umbraco icon, with v8.8.0, there's probably a better way to achieve this with an SVG icon. I'll keep that in mind. 👍

**Comment by leekelleher** [comment]
...and I wasn't aware of the `<umb-search-filter>` directive either! (re: [your PR #8179](https://github.com/umbraco/Umbraco-CMS/pull/8179)) 😀 🙌

**Comment by BatJan** [comment]
You're most welcome Lee 😊 Oh yes, good point. I did not think about the versioning at all 😅 <umb-icon> is available with the 8.8 release. I can't remember when <umb-search-filter> was introduced actually - It might have been 8.6 or 8.7 😬

Do you want me to roll some of it back or will you bump up the release number? 🙂 Just let me know. I have another draft PR that I hope to finish during the week as well. I actually only need to write about the changes made so not much that needs to be done but with a baby in the house time and memory is a thing 😂

**Comment by leekelleher** [comment]
Carry on as you are @BatJan, all good.
I'll figure out the versioning.

**Comment by leekelleher** [comment]
@BatJan Just to let you know that I've finally got around to adding some of your accessibility amends to the current version, in commit: 0f223302f091696649a6f33f94eca733674ab332. 🚀 

Once I figure out when I can bump the Umbraco dependency up beyond v8.8.0 (for the other new directives), I'll merge the rest in.  I'm hoping to ramp up my releases soon, _(the gap between v1.0 and v1.1 has felt too long for me)._

**Review by leekelleher — APPROVED** [review]
All good, thank you @BatJan! 🌟

**Comment by leekelleher** [comment]
I've decided that Contentment v2.x will build against Umbraco v8.10.0, _(once it's released)._
So I can now merge this in, thanks again!

**Pull request merged**
