### PR TITLE
Decoupling Underscore

### PR DESCRIPTION
**Pull request by Matthew-Wise**
### Description

Removes the use of underscores isEmpty and Reject functions.

As you can see by the commits I tried to use optional chaining `?.` however the minifying tool does not support this.

### Related Issues?

#39 

### Checklist

- [x] My code follows the coding style of this project.
- [x] My changes generate no new warnings.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the corresponding documentation.
- [x] I have read the **[CONTRIBUTING](CONTRIBUTING)** and **[CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)** documents.

### CODE REVIEW

**Comment by Matthew-Wise** [comment]
Will be adding some more commits to this shortly each commit ill keep small and for one file / _ function

**Comment by Matthew-Wise** [comment]
Ill leave this one for now only 2 difference under score uses left. Seems fine from my testing 🤞 your testing results in the same success

Matt

**Comment by leekelleher** [comment]
Thank you Matt! 👏 I'll review and test the changes soon.

**Comment by leekelleher** [comment]
@Matthew-Wise I'm finally at the point of starting work on v2.x, (and bumped up the Umbraco dependency).  I'm going to look at your PR today! I'll need to rebase the branch with my latest amends - nothing for you to do, but more to let you know if anything goes weird with your forked repo, (due to the rebasing, orphaned branches, etc). 🤞

**Review by leekelleher — APPROVED** [review]
All looking good! 🎉  Thanks @Matthew-Wise!
I ended up making some tweaks and amends, nothing major. I'm happy to finally merge this in.

**Pull request merged**
