### PR TITLE
Umbraco RC003 updates

### PR DESCRIPTION
**Pull request by mattbrailsford**
### Description

Updated the Umbraco dependency to RC003 and fixed build errors

### Types of changes

- [ ] Documentation change
- [x] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_

### Checklist

- [x] My code follows the coding style of this project.
- [x] My changes generate no new warnings.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the corresponding documentation.
- [x] I have read the **[CONTRIBUTING](CONTRIBUTING)** and **[CODE_OF_CONDUCT](CODE_OF_CONDUCT.md)** documents.

### CODE REVIEW

**Comment by leekelleher** [comment]
@mattbrailsford Can you rebase this on the `dev/v3.0` branch please?

_(The `dev/wip/umb9beta001` branch was my initial work, outdated now, I left it around, as it was linked to on my original dev notes. #105)_

**Comment by mattbrailsford** [comment]
I've just realised that you already have a build against RC003. I need to re-test as I was getting a migration error and thought it was an RC003 problem.

**Comment by leekelleher** [comment]
I think there was an undocumented breaking-change, (can't remember where I heard about it, either Twitter or Slack), with the migrations `Upgrader.Execute` method being changed from returning an object, to becoming a `void`.

Interestingly, I never assigned the return type, e.g. https://github.com/leekelleher/umbraco-contentment/blob/dev/v3.0/src/Umbraco.Community.Contentment/Composing/ContentmentComponent.cs#L34
but it was still a breaking-change to the API, so would throw an exception. A dependency upgrade and recompile resolved the issue for me, albeit no code changes required. 🤷 

Just checking, are you on [Contentment v3.0.0-alpha005](https://github.com/leekelleher/umbraco-contentment/releases/tag/3.0.0-alpha005)?

**Comment by mattbrailsford** [comment]
Yea, basically what happened to me too. I'm pretty sure I was on alpha005 but after making sure, it seems to work ok now 🤷‍♂️

**Comment by leekelleher** [comment]
Honestly, breaking-changes in RCs?! _(LEE, YOUR PLUGIN HAS BROKEN MY WEBSITE! 😡)_
I eagerly await v9.0.0 final release! 😆

**Pull request closed without merging**
